run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - gosec
    - gocyclo
    - dupl
    - misspell
    - lll
    - unparam
    - nakedret
    - prealloc
    - exportloopref
    - noctx
    - exhaustive

linters-settings:
  gocyclo:
    min-complexity: 15
  lll:
    line-length: 120
  gosec:
    excludes:
      - G104 # Audit errors not checked
  errcheck:
    check-blank: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - lll
